#!/bin/bash

##############################################################################
# Set passwords in etcd on controller node
##############################################################################
export ETCDCTL_ENDPOINTS="http://localhost:2379"
source /etc/profile.d/genpasswd.sh
ETCD_ADMIN_PASS=$(cat ~/.ETCD_ADMIN_PASS)
etcdctl --username admin:"$ETCD_ADMIN_PASS" mk /passwords/ADMIN_PASS $(genpasswd 16)
etcdctl --username admin:"$ETCD_ADMIN_PASS" mk /passwords/BARBICAN_DBPASS $(genpasswd 16)
etcdctl --username admin:"$ETCD_ADMIN_PASS" mk /passwords/BARBICAN_KEK $(echo $(genpasswd 32) | base64)
etcdctl --username admin:"$ETCD_ADMIN_PASS" mk /passwords/BARBICAN_PASS $(genpasswd 16)
etcdctl --username admin:"$ETCD_ADMIN_PASS" mk /passwords/CINDER_DBPASS $(genpasswd 16)
etcdctl --username admin:"$ETCD_ADMIN_PASS" mk /passwords/CINDER_PASS $(genpasswd 16)
etcdctl --username admin:"$ETCD_ADMIN_PASS" mk /passwords/DASH_DBPASS $(genpasswd 16)
etcdctl --username admin:"$ETCD_ADMIN_PASS" mk /passwords/DEMO_PASS $(genpasswd 16)
etcdctl --username admin:"$ETCD_ADMIN_PASS" mk /passwords/DESIGNATE_DBPASS $(genpasswd 16)
etcdctl --username admin:"$ETCD_ADMIN_PASS" mk /passwords/DESIGNATE_PASS $(genpasswd 16)
etcdctl --username admin:"$ETCD_ADMIN_PASS" mk /passwords/GLANCE_DBPASS $(genpasswd 16)
etcdctl --username admin:"$ETCD_ADMIN_PASS" mk /passwords/GLANCE_PASS $(genpasswd 16)
etcdctl --username admin:"$ETCD_ADMIN_PASS" mk /passwords/KEYSTONE_DBPASS $(genpasswd 16)
etcdctl --username admin:"$ETCD_ADMIN_PASS" mk /passwords/METADATA_SECRET $(genpasswd 32)
etcdctl --username admin:"$ETCD_ADMIN_PASS" mk /passwords/NEUTRON_DBPASS $(genpasswd 16)
etcdctl --username admin:"$ETCD_ADMIN_PASS" mk /passwords/NEUTRON_PASS $(genpasswd 16)
etcdctl --username admin:"$ETCD_ADMIN_PASS" mk /passwords/NOVA_DBPASS $(genpasswd 16)
etcdctl --username admin:"$ETCD_ADMIN_PASS" mk /passwords/NOVA_PASS $(genpasswd 16)
etcdctl --username admin:"$ETCD_ADMIN_PASS" mk /passwords/PLACEMENT_DBPASS $(genpasswd 16)
etcdctl --username admin:"$ETCD_ADMIN_PASS" mk /passwords/PLACEMENT_PASS $(genpasswd 16)
etcdctl --username admin:"$ETCD_ADMIN_PASS" mk /passwords/RABBIT_ADMIN_PASS $(genpasswd 16)
etcdctl --username admin:"$ETCD_ADMIN_PASS" mk /passwords/RABBIT_PASS $(genpasswd 16)
etcdctl --username admin:"$ETCD_ADMIN_PASS" mk /passwords/ROOT_DBPASS $(genpasswd 16)
etcdctl --username admin:"$ETCD_ADMIN_PASS" mk /passwords/CA_PASSWORD $(genpasswd 32)
etcdctl --username admin:"$ETCD_ADMIN_PASS" mk /passwords/COMPUTE_KEYSTORE_PASS $(genpasswd 16)
etcdctl --username admin:"$ETCD_ADMIN_PASS" mk /passwords/CONTROLLER_KEYSTORE_PASS $(genpasswd 16)
etcdctl --username admin:"$ETCD_ADMIN_PASS" mk /passwords/DS_ADMIN_PASS $(genpasswd 16)
etcdctl --username admin:"$ETCD_ADMIN_PASS" mk /passwords/DS_ROOT_PASS $(genpasswd 16)
etcdctl --username admin:"$ETCD_ADMIN_PASS" mk /passwords/KERBEROS_MASTER_SECRET $(genpasswd 32)
etcdctl --username admin:"$ETCD_ADMIN_PASS" mk /passwords/PKI_ADMIN_PASSWORD $(genpasswd 16)
etcdctl --username admin:"$ETCD_ADMIN_PASS" mk /passwords/PKI_BACKUP_PASSWORD $(genpasswd 16)
etcdctl --username admin:"$ETCD_ADMIN_PASS" mk /passwords/PKI_CLIENT_DATABASE_PASSWORD $(genpasswd 16)
etcdctl --username admin:"$ETCD_ADMIN_PASS" mk /passwords/PKI_CLIENT_PKCS12_PASSWORD $(genpasswd 16)
etcdctl --username admin:"$ETCD_ADMIN_PASS" mk /passwords/PKI_CLONE_PKCS12_PASSWORD $(genpasswd 16)
etcdctl --username admin:"$ETCD_ADMIN_PASS" mk /passwords/PKI_REPLICATION_PASSWORD $(genpasswd 16)
etcdctl --username admin:"$ETCD_ADMIN_PASS" mk /passwords/PKI_SECURITY_DOMAIN_PASSWORD $(genpasswd 16)
etcdctl --username admin:"$ETCD_ADMIN_PASS" mk /passwords/PKI_SERVER_DATABASE_PASSWORD $(genpasswd 16)
etcdctl --username admin:"$ETCD_ADMIN_PASS" mk /passwords/PKI_TOKEN_PASSWORD $(genpasswd 16)
etcdctl --username admin:"$ETCD_ADMIN_PASS" mk /passwords/IDM_ONE_KEYSTORE_PASS $(genpasswd 16)
etcdctl --username admin:"$ETCD_ADMIN_PASS" mk /passwords/IDM_TWO_KEYSTORE_PASS $(genpasswd 16)
